import Anthropic from '@anthropic-ai/sdk'
import { getTasks, saveTasks, normalizeTask } from '../tasks.js'

const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

function taskSummary(tasks) {
  const open = tasks.filter(t => !t.done)
  const done = tasks.filter(t => t.done)
  const urgent = open.filter(t => t.pri === 'urgent')
  const week = open.filter(t => t.tag === 'week')
  const areas = ['software','hardware','business','operation']
  return `CURRENT TASKS (${new Date().toLocaleDateString('id-ID', {weekday:'long', day:'numeric', month:'long', year:'numeric'})}):
Total: ${tasks.length} | Open: ${open.length} | Done: ${done.length} | Urgent: ${urgent.length} | This Week: ${week.length}

${areas.map(area => {
  const ts = open.filter(t => t.area === area)
  if (!ts.length) return null
  return `[${area.toUpperCase()}] (${ts.length} open)\n` + ts.map(t =>
    `  ${t.id} | ${t.pri==='urgent'?'🔴':'⚪'} ${t.tag==='week'?'📅':'  '} [${t.sec}] ${t.txt} (${t.owner})`
  ).join('\n')
}).filter(Boolean).join('\n\n')}

DONE (${done.length}): ${done.map(t=>t.id).join(', ') || 'none'}`
}

function formatTasksForMeeting(tasks) {
  const areas = ['software','hardware','business','operation']
  const open = tasks.filter(t => !t.done)
  const urgent = open.filter(t => t.pri === 'urgent')
  
  return `📋 *CASAN CEO MEETING BRIEF*
${new Date().toLocaleDateString('id-ID', {weekday:'long', day:'numeric', month:'long', year:'numeric'})}
━━━━━━━━━━━━━━━━━━━━━━━━━

📊 *SUMMARY*
• Total open: ${open.length} tasks
• Urgent: ${urgent.length} tasks
• Done this cycle: ${tasks.filter(t=>t.done).length} tasks

${areas.map(area => {
  const ts = open.filter(t => t.area === area)
  if (!ts.length) return null
  const urg = ts.filter(t => t.pri === 'urgent')
  const norm = ts.filter(t => t.pri !== 'urgent')
  let out = `\n🔷 *${area.toUpperCase()}* (${ts.length})\n`
  if (urg.length) out += urg.map(t => `  🔴 ${t.txt}\n     ↳ ${t.sec} · ${t.owner}`).join('\n') + '\n'
  if (norm.length) out += norm.map(t => `  ◻ ${t.txt}\n     ↳ ${t.sec} · ${t.owner}`).join('\n')
  return out
}).filter(Boolean).join('\n')}

━━━━━━━━━━━━━━━━━━━━━━━━━
_Generated by CASAN Task Board_`
}

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*')
  res.setHeader('Access-Control-Allow-Methods', 'POST,OPTIONS')
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type')
  if (req.method === 'OPTIONS') return res.status(200).end()
  if (req.method !== 'POST') return res.status(405).end()

  const { message, history = [] } = req.body
  if (!message) return res.status(400).json({ error: 'message required' })

  const tasks = await getTasks()

  const systemPrompt = `You are the CASAN CEO Task Assistant for PT CASAN Energi Indonesia. You help Will manage his task board through natural conversation.

CURRENT TASK DATA:
${taskSummary(tasks)}

CAPABILITIES - you can perform these actions by returning JSON in your response:
1. Mark task done: {"action":"patch","id":"h1","data":{"done":true}}
2. Reopen task: {"action":"patch","id":"h1","data":{"done":false}}
3. Change priority: {"action":"patch","id":"h1","data":{"pri":"urgent"}}
4. Add new task: {"action":"add","data":{"area":"hardware","sec":"Section","txt":"Task text","pri":"urgent","tag":"week","owner":"CEO"}}
5. Delete task: {"action":"delete","id":"h1"}
6. Bulk operations: {"action":"bulk","ops":[...array of above...]}

RULES:
- Always be brief and direct. Will is a CEO, not a developer.
- When performing actions, FIRST do the action JSON block, THEN confirm naturally in 1-2 sentences.
- For "meeting" or "brief" requests, return the meeting format using formatMeeting:true in your JSON.
- Match tasks by partial text, ID, or description — be smart about fuzzy matching.
- Areas: software, hardware, business, operation
- Priority: urgent, normal | Tag: week, null
- If unclear which task, list options and ask.
- Respond in the same language the user writes in (Bahasa Indonesia or English).
- For listing tasks, be concise — use short bullet format.

ACTION FORMAT: Embed JSON actions in your response like this:
\`\`\`action
{"action":"patch","id":"s1","data":{"done":true}}
\`\`\`
Then follow with your natural language confirmation.`

  try {
    const response = await client.messages.create({
      model: 'claude-opus-4-5',
      max_tokens: 1024,
      system: systemPrompt,
      messages: [
        ...history.slice(-8).map(m => ({ role: m.role, content: m.content })),
        { role: 'user', content: message }
      ]
    })

    const text = response.content[0].text
    const actionMatch = text.match(/```action\n([\s\S]*?)\n```/)
    let mutatedTasks = null
    let actionResult = null

    if (actionMatch) {
      try {
        const action = JSON.parse(actionMatch[1])
        const currentTasks = await getTasks()

        if (action.action === 'patch') {
          const idx = currentTasks.findIndex(t => t.id === action.id)
          if (idx >= 0) {
            currentTasks[idx] = normalizeTask({ ...currentTasks[idx], ...action.data, id: currentTasks[idx].id, updatedAt: new Date().toISOString() })
            await saveTasks(currentTasks)
            mutatedTasks = currentTasks
            actionResult = { type: 'patch', id: action.id }
          }
        } else if (action.action === 'add') {
          const newTask = normalizeTask({ id: `${action.data.area[0]}${Date.now()}`, done: false, createdAt: new Date().toISOString(), ...action.data })
          currentTasks.push(newTask)
          await saveTasks(currentTasks)
          mutatedTasks = currentTasks
          actionResult = { type: 'add', id: newTask.id }
        } else if (action.action === 'delete') {
          const filtered = currentTasks.filter(t => t.id !== action.id)
          await saveTasks(filtered)
          mutatedTasks = filtered
          actionResult = { type: 'delete', id: action.id }
        } else if (action.action === 'bulk') {
          for (const op of action.ops) {
            if (op.action === 'patch') {
              const idx = currentTasks.findIndex(t => t.id === op.id)
              if (idx >= 0) currentTasks[idx] = normalizeTask({ ...currentTasks[idx], ...op.data, id: currentTasks[idx].id, updatedAt: new Date().toISOString() })
            } else if (op.action === 'add') {
              currentTasks.push(normalizeTask({ id:`${op.data.area[0]}${Date.now()}`, done:false, createdAt:new Date().toISOString(), ...op.data }))
            }
          }
          await saveTasks(currentTasks)
          mutatedTasks = currentTasks
          actionResult = { type: 'bulk', count: action.ops.length }
        } else if (action.action === 'meeting') {
          actionResult = { type: 'meeting', text: formatTasksForMeeting(currentTasks) }
        }
      } catch (e) { console.error('Action parse error:', e) }
    }

    const cleanText = text.replace(/```action\n[\s\S]*?\n```\n?/g, '').trim()

    return res.status(200).json({
      reply: cleanText,
      tasks: mutatedTasks,
      action: actionResult
    })
  } catch (err) {
    console.error(err)
    return res.status(500).json({ error: 'AI error: ' + err.message })
  }
}
